### PR TITLE
Add community files

### PR DESCRIPTION
**Pull request by coopeeo**
yea i used eclipse license fuck you hahahahahaha

### CODE REVIEW

**Comment by Weebifying** [comment]
never cook again

**Comment by SpaghettDev** [comment]
ong 😭

**Comment by coopeeo** [comment]
SHUT UP WEEBIFY

**Comment by FireMario211** [comment]
hi my name is fire

**Comment by SpaghettDev** [comment]
firee do you get an identity crisis every now and then

**Pull request closed without merging**
